name: Word Counts
on:
  pull_request_target:

jobs:
  count:
    name: Word Count
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: ./
    - name: check-count
      if: env.MERGE_FAILED != '1'
      id: count
      run: git ls-files -z | xargs -0 wc
