name: Word Counts
on:
  pull_request_target:

jobs:
  count:
    name: Word Count
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: count-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: github.event_name == 'push'
      uses: actions/checkout@v2
    - name: check-count
      id: count
      run: git ls-files -z | xargs -0 wc
