name: Word Counts
on:
  pull_request_target:

jobs:
  count:
    name: Word Count
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      run: |
        if ! git fetch origin refs/pull/${{github.event.pull_request.number}}/merge; then
          echo "::notice ::Can't get merge commit… Is PR merged? If not, there's probably a conflict. Resolve it to get workflow feedback."
          echo "SKIP=1" >> $GITHUB_ENV
          exit 0
        fi
        git checkout FETCH_HEAD
    - name: check-count
      if: env.SKIP != '1'
      id: count
      run: git ls-files -z | xargs -0 wc
